### ISSUE TITLE
Network lag: Events can reach clients at different times

### ISSUE THREAD

**Issue by srikailash** [srikailash/Easterhack#4]
Identify maximum lag and investigate reasons for how lag builds up over time

**Comment by srikailash** [comment]
Also the reason for edge cases
1. Ball can go out  in session for other player and still be in the grid for one, causing restart of the game for both players
2. Same player can be at different positions triggering new game

**Comment by srikailash** [comment]
Added a timestamp in the future to actually_start event. Now, both clients start at the same time at that timestamp.

**Comment by jan25** [comment]
#7 duplicate
